spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://mysql-container:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: test1234
    driver-class-name: org.mariadb.jdbc.Driver

url:
  order-service:
#    order: http://localhost:8000/order-service/%s/orders
    order: http://ORDER-SERVICE/order-service/%s/orders
    exception:
      order_is_empty: User's order is empty.
